name: DockerHub

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGEM_DOCKERHUB: ${{ secrets.DOCKERHUB_USERNAME }}/site-indicadores-economia-2021

jobs:

  build-dockerhub:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login no Docker Hub
      uses: docker/login-action@v1.8.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build de imagem e Push no Docker Hub
      run: |
        cd ./SiteEstaticoCotacoes
        docker build . --file Dockerfile --tag ${{ env.IMAGEM_DOCKERHUB }}:latest
        docker tag ${{ env.IMAGEM_DOCKERHUB }}:latest ${{ env.IMAGEM_DOCKERHUB }}:$GITHUB_RUN_NUMBER
        docker push --all-tags ${{ env.IMAGEM_DOCKERHUB }}